//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsProcessoSeletivo
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="WsProcessoSeletivo.WSProcessoSeletivoSoap")]
    public interface WSProcessoSeletivoSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/shift.bs.WSProcSeletivo.SolicitaPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WsProcessoSeletivo.SolicitaPedidoResponse SolicitaPedido(WsProcessoSeletivo.SolicitaPedidoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/shift.bs.WSProcSeletivo.SolicitaPedido", ReplyAction="*")]
        System.Threading.Tasks.Task<WsProcessoSeletivo.SolicitaPedidoResponse> SolicitaPedidoAsync(WsProcessoSeletivo.SolicitaPedidoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.shift.com.br/processoseletivo")]
    public partial class PedidoLab
    {
        
        private string identificadorField;
        
        private Pedido pedidoField;
        
        private Paciente pacienteField;
        
        private Exame[] examesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string identificador
        {
            get
            {
                return this.identificadorField;
            }
            set
            {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Pedido pedido
        {
            get
            {
                return this.pedidoField;
            }
            set
            {
                this.pedidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Paciente paciente
        {
            get
            {
                return this.pacienteField;
            }
            set
            {
                this.pacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("exame", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Exame[] exames
        {
            get
            {
                return this.examesField;
            }
            set
            {
                this.examesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.shift.com.br/processoseletivo")]
    public partial class Pedido
    {
        
        private string codigoField;
        
        private string ordemServicoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ordemServico
        {
            get
            {
                return this.ordemServicoField;
            }
            set
            {
                this.ordemServicoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.shift.com.br/processoseletivo")]
    public partial class Exame
    {
        
        private string codigoField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descricao
        {
            get
            {
                return this.descricaoField;
            }
            set
            {
                this.descricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.shift.com.br/processoseletivo")]
    public partial class Paciente
    {
        
        private string codigoField;
        
        private string nomeField;
        
        private string sexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sexo
        {
            get
            {
                return this.sexoField;
            }
            set
            {
                this.sexoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitaPedido", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SolicitaPedidoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("pedidoLab", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WsProcessoSeletivo.PedidoLab[] Pedido;
        
        public SolicitaPedidoRequest()
        {
        }
        
        public SolicitaPedidoRequest(WsProcessoSeletivo.PedidoLab[] Pedido)
        {
            this.Pedido = Pedido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitaPedidoResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SolicitaPedidoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public bool SolicitaPedidoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string Descricao;
        
        public SolicitaPedidoResponse()
        {
        }
        
        public SolicitaPedidoResponse(bool SolicitaPedidoResult, string Descricao)
        {
            this.SolicitaPedidoResult = SolicitaPedidoResult;
            this.Descricao = Descricao;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WSProcessoSeletivoSoapChannel : WsProcessoSeletivo.WSProcessoSeletivoSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WSProcessoSeletivoSoapClient : System.ServiceModel.ClientBase<WsProcessoSeletivo.WSProcessoSeletivoSoap>, WsProcessoSeletivo.WSProcessoSeletivoSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSProcessoSeletivoSoapClient() : 
                base(WSProcessoSeletivoSoapClient.GetDefaultBinding(), WSProcessoSeletivoSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSProcessoSeletivoSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSProcessoSeletivoSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSProcessoSeletivoSoapClient.GetBindingForEndpoint(endpointConfiguration), WSProcessoSeletivoSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSProcessoSeletivoSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSProcessoSeletivoSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSProcessoSeletivoSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSProcessoSeletivoSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSProcessoSeletivoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsProcessoSeletivo.SolicitaPedidoResponse WsProcessoSeletivo.WSProcessoSeletivoSoap.SolicitaPedido(WsProcessoSeletivo.SolicitaPedidoRequest request)
        {
            return base.Channel.SolicitaPedido(request);
        }
        
        public bool SolicitaPedido(WsProcessoSeletivo.PedidoLab[] Pedido, out string Descricao)
        {
            WsProcessoSeletivo.SolicitaPedidoRequest inValue = new WsProcessoSeletivo.SolicitaPedidoRequest();
            inValue.Pedido = Pedido;
            WsProcessoSeletivo.SolicitaPedidoResponse retVal = ((WsProcessoSeletivo.WSProcessoSeletivoSoap)(this)).SolicitaPedido(inValue);
            Descricao = retVal.Descricao;
            return retVal.SolicitaPedidoResult;
        }
        
        public System.Threading.Tasks.Task<WsProcessoSeletivo.SolicitaPedidoResponse> SolicitaPedidoAsync(WsProcessoSeletivo.SolicitaPedidoRequest request)
        {
            return base.Channel.SolicitaPedidoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSProcessoSeletivoSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSProcessoSeletivoSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://177.69.214.188/shift/integracao/procseletivo/shift.bs.WSProcSeletivo.cls");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSProcessoSeletivoSoapClient.GetBindingForEndpoint(EndpointConfiguration.WSProcessoSeletivoSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSProcessoSeletivoSoapClient.GetEndpointAddress(EndpointConfiguration.WSProcessoSeletivoSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            WSProcessoSeletivoSoap,
        }
    }
}
